---
root: true
extends: ["next/core-web-vitals", "plugin:@typescript-eslint/recommended"]

parser: "@typescript-eslint/parser"

plugins: ["@typescript-eslint"]

overrides:
  - extends: ["plugin:@typescript-eslint/recommended-requiring-type-checking"]
  - files: ["*.ts", "*.tsx"]

parserOptions:
  project: "tsconfig.json"

rules:
  - "@typescript-eslint/consistent-type-imports": warn
  - consistent-type-imports:
      - warn
      - prefer: "type-imports"
      - fixStyle: "inline-type-imports"
  - no-unused-vars:
      - "warn"
      - argsIgnorePattern: "^_"
  - no-misused-promises": off
