---
name: Build

on:
  workflow_dispatch: 
    inputs: 
      repo: 
        description: "Build desired repo"
        required: false
        type: string
      app_id: 
        required: true
        type: string
      webhook_secret: 
        required: true
        type: string
      private_key: 
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
        matrix:
          node-version: [18.x]

    steps:
        
    - uses: actions/checkout@v3
    - name: "Clone user's repo"
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.repository }}
    - uses: pnpm/action-setup@0609f0983b7a228f052f81ef4c3d6510cae254ad
      with:
        version: 6.10.0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install Dependencies
      run: pnpm ci

    - name: Build
      run: pnpm build

...